Make the starter kit slightly easier to understand. Closes #8
verida/vue-starter-kit pull request #10
Opened 2022-03-07 06:24 UTC by nick-verida

2022-03-07 07:12 UTC, cmcWebCode40 requested changes

2022-03-07 07:12 UTC, cmcWebCode40 commented on src/components/Header.vue
> +      this.$emit("veridaContextSet", veridaContext)
I think the `this.$emit("veridaContextSet", veridaContext)` should exits in both the 
`src/components/Header.vue` and `src/views/SSOlogin.vue` file respectively, because both can handle login individually.

2022-03-07 07:12 UTC, cmcWebCode40 commented on src/router/index.ts
> +    // if the user is connected, local storage will have the contet name stored
small typo `contet` to `context`

2022-03-07 08:19 UTC, andy-verida reviewed
If possible, we can add more data, components to the home screen. Also, would be better to have links to the documents.

2022-03-07 08:19 UTC, andy-verida commented on src/views/Home.vue
> +import * as verida_account from "@verida/account"
this should be camel-case.

2022-03-08 00:08 UTC, nick-verida commented on src/views/Home.vue
> +import * as verida_account from "@verida/account"
[Google TypeScript styleguide](https://google.github.io/styleguide/tsguide.html#identifiers) says to use lowerCamelCase for module aliases.

I already have a `veridaAccount` variable so I've imported this as `veridaAccountModule` to make it clear. Not sure what the convention is for this, but this lets me do this

```
veridaAccount: null | veridaAccountModule.Account,
```

and I think that's pretty clear.

2022-03-08 00:09 UTC, nick-verida commented
> If possible, we can add more data, components to the home screen. Also, would be better to have links to the documents.

Yeah agree. We will enhance this, but this is more an urgent response to a community request.

2022-03-08 00:21 UTC, nick-verida commented on src/components/Header.vue
> +      this.$emit("veridaContextSet", veridaContext)
My understanding from looking at the code and testing is that the header component tests if the user is logged in and if they are it fires the `onSuccess` event. 

Or that's how it seemed I think?

What steps do I need to take to try out the login from each component?

2022-03-08 03:08 UTC, cmcWebCode40 commented on src/components/Header.vue
> +      this.$emit("veridaContextSet", veridaContext)
Yes, that's how the Header component works  it uses the `vda-account` component under the hood, while the SSOLogin component uses the `vda-login` component which has a button that's been clicked on to trigger login .

2022-03-08 03:09 UTC, nick-verida commented on src/components/Header.vue
> +      this.$emit("veridaContextSet", veridaContext)
What steps do I need to take to try out the login from each component?

2022-03-08 03:14 UTC, andy-verida commented on src/views/Home.vue
> +import * as verida_account from "@verida/account"
Looks good

2022-03-08 03:14 UTC, andy-verida approved these changes

2022-03-08 05:24 UTC, nick-verida commented on src/components/Header.vue
> +      this.$emit("veridaContextSet", veridaContext)
After some discussion with @cmcWebCode40 it looks like the components really need an update to make this work the best way possible. 

Instead I'm updating the README to say this is a work-in-progress.

2022-03-08 05:24 UTC, merged