Fix/17 set header correctly
verida/vue-starter-kit pull request #18
Opened 2022-05-06 07:55 UTC by cmcWebCode40

- [x] Fixed header profile state by updating the `@verida/vue-account` package

### Demo 

https://www.loom.com/share/0f2256946e884cefa62cb6596c1ee3d8

2022-05-07 06:39 UTC, nick-verida commented
Doesn't build

```
 ERROR  Failed to compile with 1 error                                        4:09:15 pm

 error

js/chunk-vendors.8d1a681f.js from Terser
Unexpected token: punc (.) [./node_modules/@verida/vue-account/dist/account.esm.js:142,0][js/chunk-vendors.8d1a681f.js:67124,31]

 ERROR  Build failed with errors.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

2022-05-07 06:40 UTC, nick-verida commented
I've added an action to do builds on pushes and PRs.

2022-05-07 07:08 UTC, cmcWebCode40 commented
ok, i see the problem this is related to this error here https://github.com/verida/demo-credential-issuer#readme
There's a conditional statement with optional chaining in the `vue-account` component this is the cause of the error .

2022-05-07 12:03 UTC, cmcWebCode40 commented
@nick-verida , the yarn build issue has been fixed

2022-05-09 04:00 UTC, nick-verida commented
It looks like the header is fixed, but the starter kit itself seems broken:

![image](https://user-images.githubusercontent.com/87622993/167338420-44d73831-0274-41f5-910c-7820aa9528d0.png)

2022-05-09 04:01 UTC, nick-verida requested changes
See comment

2022-05-09 04:29 UTC, cmcWebCode40 commented
@nick-verida, 

I tried to reproduce this error, but could not get the same broken page, please can you put down the steps to reproduce this error?

2022-05-09 04:47 UTC, nick-verida commented
@cmcWebCode40 I didn't do anything special. It shows the same at the 15 second point in your loom above.

2022-05-09 06:43 UTC, cmcWebCode40 commented
@nick-verida 
I have resolved this issue you stated above and refactored the code

2022-05-10 03:33 UTC, nick-verida requested changes
See comments on code and comments on the PR

2022-05-10 03:33 UTC, nick-verida commented on .env
> +VUE_APP_CONTEXT_NAME=Verida: mike app
Fix this

2022-05-10 03:33 UTC, nick-verida commented on src/components/Header.vue
> -  emits: ["veridaContextSet"]
Shouldn't we declare these events (`veridaContextSet` and `setDid`) as being emitted?

https://vuejs.org/guide/components/events.html#declaring-emitted-events

2022-05-10 03:33 UTC, nick-verida commented on src/helpers/VeridaClient.ts
> +class VeridaClientAPI {
What is this class actually for? 

It just seems to complicate things. 

The only time when it is used is to read the `did` from it, but both times that is done the DID is easily available in the code that is using it.

2022-05-10 03:33 UTC, nick-verida commented on src/views/Home.vue
> +      did: VeridaClient.did,
why is this `VeridaClient.did` and not `this.did`? 

the `setDid` method sets the did on this object, right?

2022-05-10 03:33 UTC, nick-verida commented on src/views/Home.vue
> -    veridaContext: null | verida.Context;
The purpose of this starter kit is to make is simple for people to develop using Verida. To do this they shouldn't have to go digging through other objects to get the context.

the Verida Context object is what people need. It should be available right there in the component they are developing.

2022-05-10 03:38 UTC, nick-verida commented
Ok, this is going around in circles some. 

## Verida Context

Please remove any "helper" classes that are hiding the Verida Context and make it available on `Home.vue` directly. It should be set by the events from `Header.vue` and/or `SSOLogin.vue`

We want to make this as simple as possible for people to use. That means having the Verida Context right there. 

## Login

There is still bits of code like this:

```
     //save login status in Local-storage
      // This is checked in /router/index.ts
      store.set(VUE_APP_CONTEXT_NAME, true);
```

Is that needed anymore? If not, please remove it.

2022-05-10 05:18 UTC, cmcWebCode40 commented on src/components/Header.vue
> -  emits: ["veridaContextSet"]
yes, the event should be declared, I did declare only the `setDid` event because that's was used in the child component

2022-05-10 05:24 UTC, cmcWebCode40 commented on src/helpers/VeridaClient.ts
> +class VeridaClientAPI {
The idea was to separate our verida code from the vue-component, and the class (it could just be a function)  also holds the verida contexts, and if we would want to demonstrate other capabilities of the library the logic can be done in the class/utility functions without having to modify the vue-components.

I think this makes it flexible to work in pure javascript or any other SPA framework

2022-05-10 05:25 UTC, cmcWebCode40 commented on src/views/Home.vue
> +      did: VeridaClient.did,
Because the did was saved in the `veridaClient` class

2022-05-10 05:26 UTC, cmcWebCode40 commented on src/views/Home.vue
> -    veridaContext: null | verida.Context;
ok, noted

2022-05-10 05:26 UTC, cmcWebCode40 commented
> Please remove any "helper" classes that are hiding the Verida Context and make it available on Home.vue directly. It should be set by the events from Header.vue and/or SSOLogin.vue


Alright, will make the requested changes.

2022-05-10 20:32 UTC, cmcWebCode40 commented
@nick-verida,

## 10-05-200
Progress update on the refactor concerning your comments.

I have one issue around the around the event bus i implemented,  trying to use the vue event bus to emit an event in a non-parent and child component (Home and SSOLogin) the `SSOLogin.vue` component receives the `context` emit an event passing the `context` 
and it's been listened to in the Home component but this didn't work here is a similar issue on [stackoverflow](https://stackoverflow.com/questions/58554365/how-do-you-eventbus-a-bus-to-communicate-updates-to-a-view-in-a-vue-component). because the `SSOLogin.vue` screen routes to the home screen and the event listener  in the `Home.vue` screen can't catch the `context`

I'm to avoiding using `vuex` because to goal is to keep code examples simple.

2022-05-11 20:05 UTC, cmcWebCode40 commented
@nick-verida,

the other solution I saw was using local storage but I don't think is a good practice in this use case, so I had to fall back to using `vuex` to manage state and this works fine. but still trying to get an alternative. 

please are your thoughts on this?

2022-05-18 22:43 UTC, merged